# Generated by Django 5.0.2 on 2024-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_make_brands_remove_make_is_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
