# Generated by Django 5.0.2 on 2024-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_make_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/phones/images'),
        ),
    ]
