# Generated by Django 5.0.2 on 2024-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
